enum {
    PIT_CRYSTAL_HZ = 1193182,

    CLOCK_PRECISION_HZ = 100,

    PIT_PROGRAM_REG = PIT_CRYSTAL_HZ / CLOCK_PRECISION_HZ,

    PIT_SELECT_CHANNEL0 = 0x0,
    PIT_SELECT_CHANNEL1 = 0x1,
    PIT_SELECT_CHANNEL2 = 0x2,
    PIT_SELECT_CHANNEL_RB = 0x3,
    PIT_ACCESS_MODE_LATCH_COUNT_VALUE_COMMAND = 0x0,
    PIT_ACCESS_MODE_LOBYTE_ONLY = 0x1,
    PIT_ACCESS_MODE_HIBYTE_ONLY = 0x2,
    PIT_ACCESS_MODE_LOHIBYTE = 0x3,
    PIT_MODE_INTERRUPT_ON_TERMINAL_COUNT = 0x0,
    PIT_MODE_HW_ONESHOT = 0x1,
    PIT_MODE_RATE_GENERATOR = 0x2,
    PIT_MODES_SQUARE_WAVE_GENERATOR = 0x3,
    PIT_MODES_SW_TRIGGERRED_STROBE = 0x4,
    PIT_MODES_HW_TRIGGERRED_STROBE = 0x5,
};



void init_pit();

void msleep(int ms);